import messages from "../locales/messages";

const profile = {
  firstName: "Elton",
  lastName: "Lucien",
  jobTitle: messages.softwareEngineer,
  bio: messages.bio,
  aboutMeMessage: messages.aboutMeMessage,
  email: "contact@eltonlucien.com",
  phone: "7864064185",
  location: "Miami, FL",
  img: "https://avatars.githubusercontent.com/u/61792119?v=4",
  links: {
    github: "https://github.com/Elton360",
    linkedin: "https://linkedin.com/in/elton-lucien-b739348b",
    spotify: "https://open.spotify.com/user/ba8p1wtfbr4nlg65ardpmyn8a",
  },
  experiences: [
    {
      name: "Kaseya (Datto)",
      title: messages.softwareEngineer,
      from: "2022",
      tags: [
        "React",
        "TypeScript",
        "AntD",
        "Node",
        "Express",
        "GraphQL",
        "Java",
        "Spring Boot",
      ],
      text: messages.experience_1,
    },
    {
      name: "Freelance",
      title: messages.webDeveloper,
      from: "2020",
      to: "2022",
      text: messages.experience_2,
      tags: [
        "HTML",
        "CSS",
        "JavaScript",
        "React",
        "TypeScript",
        "Node",
        "Express",
        "AntD",
        "SCSS",
        "Firebase",
        "SQL",
        "MongoDB",
      ],
    },
  ],
  projects: [
    {
      imageSrc: "work/ley.png",
      title: messages.carRental,
      link: "https://leyrental.com",
      isWebsite: true,
      description: messages.work_1,
      tags: ["HTML", "CSS", "JavaScript", "Next", "Firebase"],
    },
    {
      imageSrc: "work/clubs.png",
      title: messages.ecommerce,
      link: "https://clubstees.com",
      isWebsite: true,
      description: messages.work_2,
      tags: ["HTML", "CSS", "JavaScript", "Next", "Firebase"],
    },
    {
      imageSrc: "work/unique.png",
      title: messages.restaurant,
      link: "https://uniquecaribbeanrestaurant.com",
      isWebsite: true,
      description: messages.work_3,
      tags: ["HTML", "CSS", "JavaScript", "React", "Firebase"],
    },
    {
      imageSrc: "work/lausim.png",
      title: messages.realEstate,
      link: "https://lausim.com",
      isWebsite: true,
      description: messages.work_4,
      tags: ["HTML", "CSS", "JavaScript", "React"],
    },
    {
      imageSrc: "work/bethel.png",
      title: messages.community,
      link: "https://eglisebethel.org",
      isWebsite: true,
      description: messages.work_5,
      tags: ["HTML", "CSS", "JavaScript"],
    },
    {
      imageSrc: "work/dasmain.png",
      title: messages.music,
      link: "https://yeaboiii.com",
      isWebsite: true,
      description: messages.work_6,
      tags: ["HTML", "CSS", "JavaScript"],
    },
  ],
};

export default profile;
