import messages from "../locales/messages";

const profile = {
  firstName: "John",
  lastName: "Doe",
  jobTitle: messages.softwareEngineer,
  bio: messages.bio,
  aboutMeMessage: messages.aboutMeMessage,
  email: "contact@example.com",
  phone: "1234567890",
  location: "City, Country",
  img: "https://randomuser.me/api/portraits/women/25.jpg",
  links: {
    github: "https://github.com/username",
    spotify: "https://open.spotify.com/user/username",
  },
  experiences: [
    {
      name: "Company A",
      title: messages.softwareEngineer,
      from: "2022",
      text: messages.experience_1,
      tags: [
        "React",
        "TypeScript",
        "AntD",
        "Node",
        "Express",
        "GraphQL",
        "Java",
        "Spring Boot",
      ],
    },
    {
      name: "Freelance",
      title: messages.webDeveloper,
      from: "2020",
      to: "2022",
      text: messages.experience_2,
      tags: [
        "HTML",
        "CSS",
        "JavaScript",
        "React",
        "TypeScript",
        "Node",
        "Express",
        "AntD",
        "SCSS",
        "Firebase",
        "SQL",
        "MongoDB",
      ],
    },
  ],
  projects: [
    {
      imageSrc: "https://picsum.photos/200",
      title: messages.ecommerce,
      link: "https://example.com/project1",
      isWebsite: true,
      description: messages.work_1,
      tags: ["HTML", "CSS", "JavaScript", "Next", "Firebase"],
    },
    {
      imageSrc: "https://picsum.photos/300",
      title: messages.ecommerce,
      link: "https://example.com/project2",
      isWebsite: true,
      description: messages.work_2,
      tags: ["HTML", "CSS", "JavaScript", "Next", "Firebase"],
    },
    {
      imageSrc: "https://picsum.photos/400",
      title: messages.ecommerce,
      link: "https://example.com/project3",
      isWebsite: true,
      description: messages.work_3,
      tags: ["HTML", "CSS", "JavaScript", "React", "Firebase"],
    },
    {
      imageSrc: "https://picsum.photos/500",
      title: messages.ecommerce,
      link: "https://example.com/project4",
      isWebsite: true,
      description: messages.work_4,
      tags: ["HTML", "CSS", "JavaScript", "React"],
    },
  ],
};

export default profile;
